export {default as Hero} from './Hero'
export {default as Mailchimp} from './Mailchimp'
export {default as TextSection} from './TextSection'
export {default as ImageSection} from './ImageSection'
export {default as PortfolioSection} from './PortfolioSection'
export {default as TeamSection} from './TeamSection'
export {default as NewsSection} from './NewsSection'
